on: [push, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  commit-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: ./artifact

      - name: Move artifact to root
        run: mv ./artifact/firmware.zip ./firmware.zip

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit artifact
        run: |
          git add firmware.zip
          git commit -m "Add build artifact"
          git push
